### PR TITLE
Merging advanced stories

### PR DESCRIPTION
**Pull request by amodsamant**

### CODE REVIEW

**Comment by codepathreview** [comment]
Hello Amod,

Please update your `README.md` to include a GIF or video walkthrough [as described here](https://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments#heading-creating-the-project-readme) and then [re-submit your project](https://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments#heading-submitting-through-course-system) through the course system.

**Comment by amodsamant** [comment]
Hi,

I have already submitted the video link in the portal. Its a dropbox link.

I am also pasting the link here.

https://www.dropbox.com/s/1jhuujdyej8qdll/Flicks%20App.mp4?dl=0

As this is a large file, it added it to dropbox.

Please let me know if I should re-submit or add anywhere

Thanks,
Amod

**Comment by nesquena** [comment]
@amodsamant I believe they are referring to your README.md as you should always have a link to the GIF or mp4 inside the README itself. https://hackmd.io/s/BJToUHm1l#submitting1

**Comment by amodsamant** [comment]
I have updated the README.md with the video link and gif.

On Sun, Mar 12, 2017 at 11:00 PM, Nathan Esquenazi <notifications@github.com

**Pull request merged**
